[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_splitter = "8XehsmJccsRtvkisTNKC8JHsecAvY8rALoYf1N3xjjjJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
